// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: parallax.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_Ping_FullMethodName = "/parallax.WorkerService/Ping"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Core Worker Service
// =============================================================================
type WorkerServiceClient interface {
	Ping(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) Ping(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, WorkerService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// =============================================================================
// Core Worker Service
// =============================================================================
type WorkerServiceServer interface {
	Ping(context.Context, *GenericRequest) (*GenericResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) Ping(context.Context, *GenericRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Ping(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WorkerService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parallax.proto",
}

const (
	LoadTestService_RunLoadTest_FullMethodName   = "/parallax.LoadTestService/RunLoadTest"
	LoadTestService_StopLoadTest_FullMethodName  = "/parallax.LoadTestService/StopLoadTest"
	LoadTestService_GetLastResult_FullMethodName = "/parallax.LoadTestService/GetLastResult"
)

// LoadTestServiceClient is the client API for LoadTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Load Test Service
// =============================================================================
type LoadTestServiceClient interface {
	RunLoadTest(ctx context.Context, in *LoadTestConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoadTestProgress], error)
	StopLoadTest(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetLastResult(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*LoadTestResult, error)
}

type loadTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadTestServiceClient(cc grpc.ClientConnInterface) LoadTestServiceClient {
	return &loadTestServiceClient{cc}
}

func (c *loadTestServiceClient) RunLoadTest(ctx context.Context, in *LoadTestConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LoadTestProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LoadTestService_ServiceDesc.Streams[0], LoadTestService_RunLoadTest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LoadTestConfig, LoadTestProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoadTestService_RunLoadTestClient = grpc.ServerStreamingClient[LoadTestProgress]

func (c *loadTestServiceClient) StopLoadTest(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, LoadTestService_StopLoadTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadTestServiceClient) GetLastResult(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*LoadTestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadTestResult)
	err := c.cc.Invoke(ctx, LoadTestService_GetLastResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadTestServiceServer is the server API for LoadTestService service.
// All implementations must embed UnimplementedLoadTestServiceServer
// for forward compatibility.
//
// =============================================================================
// Load Test Service
// =============================================================================
type LoadTestServiceServer interface {
	RunLoadTest(*LoadTestConfig, grpc.ServerStreamingServer[LoadTestProgress]) error
	StopLoadTest(context.Context, *StopRequest) (*GenericResponse, error)
	GetLastResult(context.Context, *GenericRequest) (*LoadTestResult, error)
	mustEmbedUnimplementedLoadTestServiceServer()
}

// UnimplementedLoadTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadTestServiceServer struct{}

func (UnimplementedLoadTestServiceServer) RunLoadTest(*LoadTestConfig, grpc.ServerStreamingServer[LoadTestProgress]) error {
	return status.Error(codes.Unimplemented, "method RunLoadTest not implemented")
}
func (UnimplementedLoadTestServiceServer) StopLoadTest(context.Context, *StopRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopLoadTest not implemented")
}
func (UnimplementedLoadTestServiceServer) GetLastResult(context.Context, *GenericRequest) (*LoadTestResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastResult not implemented")
}
func (UnimplementedLoadTestServiceServer) mustEmbedUnimplementedLoadTestServiceServer() {}
func (UnimplementedLoadTestServiceServer) testEmbeddedByValue()                         {}

// UnsafeLoadTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadTestServiceServer will
// result in compilation errors.
type UnsafeLoadTestServiceServer interface {
	mustEmbedUnimplementedLoadTestServiceServer()
}

func RegisterLoadTestServiceServer(s grpc.ServiceRegistrar, srv LoadTestServiceServer) {
	// If the following call panics, it indicates UnimplementedLoadTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadTestService_ServiceDesc, srv)
}

func _LoadTestService_RunLoadTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadTestConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoadTestServiceServer).RunLoadTest(m, &grpc.GenericServerStream[LoadTestConfig, LoadTestProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LoadTestService_RunLoadTestServer = grpc.ServerStreamingServer[LoadTestProgress]

func _LoadTestService_StopLoadTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).StopLoadTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_StopLoadTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).StopLoadTest(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadTestService_GetLastResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadTestServiceServer).GetLastResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadTestService_GetLastResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadTestServiceServer).GetLastResult(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadTestService_ServiceDesc is the grpc.ServiceDesc for LoadTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.LoadTestService",
	HandlerType: (*LoadTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopLoadTest",
			Handler:    _LoadTestService_StopLoadTest_Handler,
		},
		{
			MethodName: "GetLastResult",
			Handler:    _LoadTestService_GetLastResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunLoadTest",
			Handler:       _LoadTestService_RunLoadTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parallax.proto",
}

const (
	HealthService_AddTarget_FullMethodName     = "/parallax.HealthService/AddTarget"
	HealthService_RemoveTarget_FullMethodName  = "/parallax.HealthService/RemoveTarget"
	HealthService_GetStatuses_FullMethodName   = "/parallax.HealthService/GetStatuses"
	HealthService_WatchStatuses_FullMethodName = "/parallax.HealthService/WatchStatuses"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Health Monitor Service
// =============================================================================
type HealthServiceClient interface {
	AddTarget(ctx context.Context, in *ServiceTarget, opts ...grpc.CallOption) (*GenericResponse, error)
	RemoveTarget(ctx context.Context, in *TargetIDRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetStatuses(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*HealthStatusList, error)
	WatchStatuses(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceStatus], error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) AddTarget(ctx context.Context, in *ServiceTarget, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, HealthService_AddTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) RemoveTarget(ctx context.Context, in *TargetIDRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, HealthService_RemoveTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetStatuses(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*HealthStatusList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthStatusList)
	err := c.cc.Invoke(ctx, HealthService_GetStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) WatchStatuses(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServiceStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthService_ServiceDesc.Streams[0], HealthService_WatchStatuses_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenericRequest, ServiceStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_WatchStatusesClient = grpc.ServerStreamingClient[ServiceStatus]

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
//
// =============================================================================
// Health Monitor Service
// =============================================================================
type HealthServiceServer interface {
	AddTarget(context.Context, *ServiceTarget) (*GenericResponse, error)
	RemoveTarget(context.Context, *TargetIDRequest) (*GenericResponse, error)
	GetStatuses(context.Context, *GenericRequest) (*HealthStatusList, error)
	WatchStatuses(*GenericRequest, grpc.ServerStreamingServer[ServiceStatus]) error
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) AddTarget(context.Context, *ServiceTarget) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTarget not implemented")
}
func (UnimplementedHealthServiceServer) RemoveTarget(context.Context, *TargetIDRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTarget not implemented")
}
func (UnimplementedHealthServiceServer) GetStatuses(context.Context, *GenericRequest) (*HealthStatusList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatuses not implemented")
}
func (UnimplementedHealthServiceServer) WatchStatuses(*GenericRequest, grpc.ServerStreamingServer[ServiceStatus]) error {
	return status.Error(codes.Unimplemented, "method WatchStatuses not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_AddTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceTarget)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).AddTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_AddTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).AddTarget(ctx, req.(*ServiceTarget))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_RemoveTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).RemoveTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_RemoveTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).RemoveTarget(ctx, req.(*TargetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetStatuses(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_WatchStatuses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenericRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HealthServiceServer).WatchStatuses(m, &grpc.GenericServerStream[GenericRequest, ServiceStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_WatchStatusesServer = grpc.ServerStreamingServer[ServiceStatus]

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTarget",
			Handler:    _HealthService_AddTarget_Handler,
		},
		{
			MethodName: "RemoveTarget",
			Handler:    _HealthService_RemoveTarget_Handler,
		},
		{
			MethodName: "GetStatuses",
			Handler:    _HealthService_GetStatuses_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatuses",
			Handler:       _HealthService_WatchStatuses_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parallax.proto",
}

const (
	WatcherService_WatchWorkspace_FullMethodName   = "/parallax.WatcherService/WatchWorkspace"
	WatcherService_UnwatchWorkspace_FullMethodName = "/parallax.WatcherService/UnwatchWorkspace"
)

// WatcherServiceClient is the client API for WatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Watcher Service
// =============================================================================
type WatcherServiceClient interface {
	WatchWorkspace(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChangeEvent], error)
	UnwatchWorkspace(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type watcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatcherServiceClient(cc grpc.ClientConnInterface) WatcherServiceClient {
	return &watcherServiceClient{cc}
}

func (c *watcherServiceClient) WatchWorkspace(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WatcherService_ServiceDesc.Streams[0], WatcherService_WatchWorkspace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, FileChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatcherService_WatchWorkspaceClient = grpc.ServerStreamingClient[FileChangeEvent]

func (c *watcherServiceClient) UnwatchWorkspace(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, WatcherService_UnwatchWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatcherServiceServer is the server API for WatcherService service.
// All implementations must embed UnimplementedWatcherServiceServer
// for forward compatibility.
//
// =============================================================================
// Watcher Service
// =============================================================================
type WatcherServiceServer interface {
	WatchWorkspace(*WatchRequest, grpc.ServerStreamingServer[FileChangeEvent]) error
	UnwatchWorkspace(context.Context, *WatchRequest) (*GenericResponse, error)
	mustEmbedUnimplementedWatcherServiceServer()
}

// UnimplementedWatcherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatcherServiceServer struct{}

func (UnimplementedWatcherServiceServer) WatchWorkspace(*WatchRequest, grpc.ServerStreamingServer[FileChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchWorkspace not implemented")
}
func (UnimplementedWatcherServiceServer) UnwatchWorkspace(context.Context, *WatchRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnwatchWorkspace not implemented")
}
func (UnimplementedWatcherServiceServer) mustEmbedUnimplementedWatcherServiceServer() {}
func (UnimplementedWatcherServiceServer) testEmbeddedByValue()                        {}

// UnsafeWatcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatcherServiceServer will
// result in compilation errors.
type UnsafeWatcherServiceServer interface {
	mustEmbedUnimplementedWatcherServiceServer()
}

func RegisterWatcherServiceServer(s grpc.ServiceRegistrar, srv WatcherServiceServer) {
	// If the following call panics, it indicates UnimplementedWatcherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatcherService_ServiceDesc, srv)
}

func _WatcherService_WatchWorkspace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WatcherServiceServer).WatchWorkspace(m, &grpc.GenericServerStream[WatchRequest, FileChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatcherService_WatchWorkspaceServer = grpc.ServerStreamingServer[FileChangeEvent]

func _WatcherService_UnwatchWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherServiceServer).UnwatchWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatcherService_UnwatchWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherServiceServer).UnwatchWorkspace(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatcherService_ServiceDesc is the grpc.ServiceDesc for WatcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.WatcherService",
	HandlerType: (*WatcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnwatchWorkspace",
			Handler:    _WatcherService_UnwatchWorkspace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchWorkspace",
			Handler:       _WatcherService_WatchWorkspace_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parallax.proto",
}

const (
	ProxyService_GetTraffic_FullMethodName   = "/parallax.ProxyService/GetTraffic"
	ProxyService_WatchTraffic_FullMethodName = "/parallax.ProxyService/WatchTraffic"
	ProxyService_ClearTraffic_FullMethodName = "/parallax.ProxyService/ClearTraffic"
	ProxyService_SetFilter_FullMethodName    = "/parallax.ProxyService/SetFilter"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Proxy Service
// =============================================================================
type ProxyServiceClient interface {
	GetTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficList, error)
	WatchTraffic(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficEntry], error)
	ClearTraffic(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	SetFilter(ctx context.Context, in *TrafficFilter, opts ...grpc.CallOption) (*GenericResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) GetTraffic(ctx context.Context, in *TrafficRequest, opts ...grpc.CallOption) (*TrafficList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficList)
	err := c.cc.Invoke(ctx, ProxyService_GetTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) WatchTraffic(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TrafficEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyService_ServiceDesc.Streams[0], ProxyService_WatchTraffic_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenericRequest, TrafficEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_WatchTrafficClient = grpc.ServerStreamingClient[TrafficEntry]

func (c *proxyServiceClient) ClearTraffic(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, ProxyService_ClearTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) SetFilter(ctx context.Context, in *TrafficFilter, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, ProxyService_SetFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
//
// =============================================================================
// Proxy Service
// =============================================================================
type ProxyServiceServer interface {
	GetTraffic(context.Context, *TrafficRequest) (*TrafficList, error)
	WatchTraffic(*GenericRequest, grpc.ServerStreamingServer[TrafficEntry]) error
	ClearTraffic(context.Context, *GenericRequest) (*GenericResponse, error)
	SetFilter(context.Context, *TrafficFilter) (*GenericResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) GetTraffic(context.Context, *TrafficRequest) (*TrafficList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraffic not implemented")
}
func (UnimplementedProxyServiceServer) WatchTraffic(*GenericRequest, grpc.ServerStreamingServer[TrafficEntry]) error {
	return status.Error(codes.Unimplemented, "method WatchTraffic not implemented")
}
func (UnimplementedProxyServiceServer) ClearTraffic(context.Context, *GenericRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTraffic not implemented")
}
func (UnimplementedProxyServiceServer) SetFilter(context.Context, *TrafficFilter) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFilter not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_GetTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_GetTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetTraffic(ctx, req.(*TrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_WatchTraffic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenericRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyServiceServer).WatchTraffic(m, &grpc.GenericServerStream[GenericRequest, TrafficEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_WatchTrafficServer = grpc.ServerStreamingServer[TrafficEntry]

func _ProxyService_ClearTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).ClearTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_ClearTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).ClearTraffic(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_SetFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).SetFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_SetFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).SetFilter(ctx, req.(*TrafficFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTraffic",
			Handler:    _ProxyService_GetTraffic_Handler,
		},
		{
			MethodName: "ClearTraffic",
			Handler:    _ProxyService_ClearTraffic_Handler,
		},
		{
			MethodName: "SetFilter",
			Handler:    _ProxyService_SetFilter_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTraffic",
			Handler:       _ProxyService_WatchTraffic_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parallax.proto",
}

const (
	MockService_AddRule_FullMethodName    = "/parallax.MockService/AddRule"
	MockService_RemoveRule_FullMethodName = "/parallax.MockService/RemoveRule"
	MockService_ListRules_FullMethodName  = "/parallax.MockService/ListRules"
)

// MockServiceClient is the client API for MockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Mock Service
// =============================================================================
type MockServiceClient interface {
	AddRule(ctx context.Context, in *MockRule, opts ...grpc.CallOption) (*GenericResponse, error)
	RemoveRule(ctx context.Context, in *TargetIDRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ListRules(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*MockRuleList, error)
}

type mockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMockServiceClient(cc grpc.ClientConnInterface) MockServiceClient {
	return &mockServiceClient{cc}
}

func (c *mockServiceClient) AddRule(ctx context.Context, in *MockRule, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, MockService_AddRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) RemoveRule(ctx context.Context, in *TargetIDRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, MockService_RemoveRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockServiceClient) ListRules(ctx context.Context, in *GenericRequest, opts ...grpc.CallOption) (*MockRuleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockRuleList)
	err := c.cc.Invoke(ctx, MockService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockServiceServer is the server API for MockService service.
// All implementations must embed UnimplementedMockServiceServer
// for forward compatibility.
//
// =============================================================================
// Mock Service
// =============================================================================
type MockServiceServer interface {
	AddRule(context.Context, *MockRule) (*GenericResponse, error)
	RemoveRule(context.Context, *TargetIDRequest) (*GenericResponse, error)
	ListRules(context.Context, *GenericRequest) (*MockRuleList, error)
	mustEmbedUnimplementedMockServiceServer()
}

// UnimplementedMockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockServiceServer struct{}

func (UnimplementedMockServiceServer) AddRule(context.Context, *MockRule) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRule not implemented")
}
func (UnimplementedMockServiceServer) RemoveRule(context.Context, *TargetIDRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRule not implemented")
}
func (UnimplementedMockServiceServer) ListRules(context.Context, *GenericRequest) (*MockRuleList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedMockServiceServer) mustEmbedUnimplementedMockServiceServer() {}
func (UnimplementedMockServiceServer) testEmbeddedByValue()                     {}

// UnsafeMockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockServiceServer will
// result in compilation errors.
type UnsafeMockServiceServer interface {
	mustEmbedUnimplementedMockServiceServer()
}

func RegisterMockServiceServer(s grpc.ServiceRegistrar, srv MockServiceServer) {
	// If the following call panics, it indicates UnimplementedMockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockService_ServiceDesc, srv)
}

func _MockService_AddRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockRule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).AddRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_AddRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).AddRule(ctx, req.(*MockRule))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_RemoveRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).RemoveRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_RemoveRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).RemoveRule(ctx, req.(*TargetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenericRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServiceServer).ListRules(ctx, req.(*GenericRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockService_ServiceDesc is the grpc.ServiceDesc for MockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.MockService",
	HandlerType: (*MockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRule",
			Handler:    _MockService_AddRule_Handler,
		},
		{
			MethodName: "RemoveRule",
			Handler:    _MockService_RemoveRule_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _MockService_ListRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parallax.proto",
}

const (
	AIService_GenerateTests_FullMethodName    = "/parallax.AIService/GenerateTests"
	AIService_RepairRequest_FullMethodName    = "/parallax.AIService/RepairRequest"
	AIService_GenerateScript_FullMethodName   = "/parallax.AIService/GenerateScript"
	AIService_CreateCollection_FullMethodName = "/parallax.AIService/CreateCollection"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// AI Service
// =============================================================================
type AIServiceClient interface {
	GenerateTests(ctx context.Context, in *AITestRequest, opts ...grpc.CallOption) (*AITestResponse, error)
	RepairRequest(ctx context.Context, in *AIRepairRequest, opts ...grpc.CallOption) (*AIRepairResponse, error)
	GenerateScript(ctx context.Context, in *AIScriptRequest, opts ...grpc.CallOption) (*AIScriptResponse, error)
	CreateCollection(ctx context.Context, in *AICollectionRequest, opts ...grpc.CallOption) (*AICollectionResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GenerateTests(ctx context.Context, in *AITestRequest, opts ...grpc.CallOption) (*AITestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AITestResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) RepairRequest(ctx context.Context, in *AIRepairRequest, opts ...grpc.CallOption) (*AIRepairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIRepairResponse)
	err := c.cc.Invoke(ctx, AIService_RepairRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateScript(ctx context.Context, in *AIScriptRequest, opts ...grpc.CallOption) (*AIScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIScriptResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) CreateCollection(ctx context.Context, in *AICollectionRequest, opts ...grpc.CallOption) (*AICollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AICollectionResponse)
	err := c.cc.Invoke(ctx, AIService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// =============================================================================
// AI Service
// =============================================================================
type AIServiceServer interface {
	GenerateTests(context.Context, *AITestRequest) (*AITestResponse, error)
	RepairRequest(context.Context, *AIRepairRequest) (*AIRepairResponse, error)
	GenerateScript(context.Context, *AIScriptRequest) (*AIScriptResponse, error)
	CreateCollection(context.Context, *AICollectionRequest) (*AICollectionResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) GenerateTests(context.Context, *AITestRequest) (*AITestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTests not implemented")
}
func (UnimplementedAIServiceServer) RepairRequest(context.Context, *AIRepairRequest) (*AIRepairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RepairRequest not implemented")
}
func (UnimplementedAIServiceServer) GenerateScript(context.Context, *AIScriptRequest) (*AIScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateScript not implemented")
}
func (UnimplementedAIServiceServer) CreateCollection(context.Context, *AICollectionRequest) (*AICollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GenerateTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AITestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateTests(ctx, req.(*AITestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_RepairRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).RepairRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_RepairRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).RepairRequest(ctx, req.(*AIRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateScript(ctx, req.(*AIScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AICollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CreateCollection(ctx, req.(*AICollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateTests",
			Handler:    _AIService_GenerateTests_Handler,
		},
		{
			MethodName: "RepairRequest",
			Handler:    _AIService_RepairRequest_Handler,
		},
		{
			MethodName: "GenerateScript",
			Handler:    _AIService_GenerateScript_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _AIService_CreateCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parallax.proto",
}

const (
	RunnerService_RunCollection_FullMethodName = "/parallax.RunnerService/RunCollection"
)

// RunnerServiceClient is the client API for RunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// Runner Service
// =============================================================================
type RunnerServiceClient interface {
	RunCollection(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
}

type runnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerServiceClient(cc grpc.ClientConnInterface) RunnerServiceClient {
	return &runnerServiceClient{cc}
}

func (c *runnerServiceClient) RunCollection(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerService_ServiceDesc.Streams[0], RunnerService_RunCollection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_RunCollectionClient = grpc.ServerStreamingClient[RunEvent]

// RunnerServiceServer is the server API for RunnerService service.
// All implementations must embed UnimplementedRunnerServiceServer
// for forward compatibility.
//
// =============================================================================
// Runner Service
// =============================================================================
type RunnerServiceServer interface {
	RunCollection(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error
	mustEmbedUnimplementedRunnerServiceServer()
}

// UnimplementedRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnerServiceServer struct{}

func (UnimplementedRunnerServiceServer) RunCollection(*RunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method RunCollection not implemented")
}
func (UnimplementedRunnerServiceServer) mustEmbedUnimplementedRunnerServiceServer() {}
func (UnimplementedRunnerServiceServer) testEmbeddedByValue()                       {}

// UnsafeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerServiceServer will
// result in compilation errors.
type UnsafeRunnerServiceServer interface {
	mustEmbedUnimplementedRunnerServiceServer()
}

func RegisterRunnerServiceServer(s grpc.ServiceRegistrar, srv RunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnerService_ServiceDesc, srv)
}

func _RunnerService_RunCollection_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunnerServiceServer).RunCollection(m, &grpc.GenericServerStream[RunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunnerService_RunCollectionServer = grpc.ServerStreamingServer[RunEvent]

// RunnerService_ServiceDesc is the grpc.ServiceDesc for RunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parallax.RunnerService",
	HandlerType: (*RunnerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunCollection",
			Handler:       _RunnerService_RunCollection_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "parallax.proto",
}
