// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: parallax.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadTestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Concurrent    int32                  `protobuf:"varint,5,opt,name=concurrent,proto3" json:"concurrent,omitempty"`
	TotalRequests int32                  `protobuf:"varint,6,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	DurationSec   int32                  `protobuf:"varint,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTestConfig) Reset() {
	*x = LoadTestConfig{}
	mi := &file_parallax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestConfig) ProtoMessage() {}

func (x *LoadTestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestConfig.ProtoReflect.Descriptor instead.
func (*LoadTestConfig) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{0}
}

func (x *LoadTestConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LoadTestConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LoadTestConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *LoadTestConfig) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LoadTestConfig) GetConcurrent() int32 {
	if x != nil {
		return x.Concurrent
	}
	return 0
}

func (x *LoadTestConfig) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *LoadTestConfig) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type LoadTestProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     int64                  `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	CurrentRps    float64                `protobuf:"fixed64,3,opt,name=current_rps,json=currentRps,proto3" json:"current_rps,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Result        *LoadTestResult        `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTestProgress) Reset() {
	*x = LoadTestProgress{}
	mi := &file_parallax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTestProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestProgress) ProtoMessage() {}

func (x *LoadTestProgress) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestProgress.ProtoReflect.Descriptor instead.
func (*LoadTestProgress) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{1}
}

func (x *LoadTestProgress) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *LoadTestProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LoadTestProgress) GetCurrentRps() float64 {
	if x != nil {
		return x.CurrentRps
	}
	return 0
}

func (x *LoadTestProgress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *LoadTestProgress) GetResult() *LoadTestResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type LoadTestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	Successful    int64                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P50LatencyMs  float64                `protobuf:"fixed64,5,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,6,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs  float64                `protobuf:"fixed64,7,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	MinLatencyMs  float64                `protobuf:"fixed64,8,opt,name=min_latency_ms,json=minLatencyMs,proto3" json:"min_latency_ms,omitempty"`
	MaxLatencyMs  float64                `protobuf:"fixed64,9,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	ReqsPerSec    float64                `protobuf:"fixed64,10,opt,name=reqs_per_sec,json=reqsPerSec,proto3" json:"reqs_per_sec,omitempty"`
	Errors        []string               `protobuf:"bytes,11,rep,name=errors,proto3" json:"errors,omitempty"`
	Histogram     []int64                `protobuf:"varint,12,rep,packed,name=histogram,proto3" json:"histogram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTestResult) Reset() {
	*x = LoadTestResult{}
	mi := &file_parallax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestResult) ProtoMessage() {}

func (x *LoadTestResult) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestResult.ProtoReflect.Descriptor instead.
func (*LoadTestResult) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{2}
}

func (x *LoadTestResult) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *LoadTestResult) GetSuccessful() int64 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *LoadTestResult) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *LoadTestResult) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetMinLatencyMs() float64 {
	if x != nil {
		return x.MinLatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetMaxLatencyMs() float64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *LoadTestResult) GetReqsPerSec() float64 {
	if x != nil {
		return x.ReqsPerSec
	}
	return 0
}

func (x *LoadTestResult) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *LoadTestResult) GetHistogram() []int64 {
	if x != nil {
		return x.Histogram
	}
	return nil
}

type ServiceTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	IntervalSec   int32                  `protobuf:"varint,4,opt,name=interval_sec,json=intervalSec,proto3" json:"interval_sec,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTarget) Reset() {
	*x = ServiceTarget{}
	mi := &file_parallax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTarget) ProtoMessage() {}

func (x *ServiceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTarget.ProtoReflect.Descriptor instead.
func (*ServiceTarget) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceTarget) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServiceTarget) GetIntervalSec() int32 {
	if x != nil {
		return x.IntervalSec
	}
	return 0
}

func (x *ServiceTarget) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	StatusCode    int32                  `protobuf:"varint,6,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LastChecked   int64                  `protobuf:"varint,7,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,8,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_parallax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceStatus) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServiceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceStatus) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ServiceStatus) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ServiceStatus) GetLastChecked() int64 {
	if x != nil {
		return x.LastChecked
	}
	return 0
}

func (x *ServiceStatus) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type HealthStatusList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ServiceStatus       `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatusList) Reset() {
	*x = HealthStatusList{}
	mi := &file_parallax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatusList) ProtoMessage() {}

func (x *HealthStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatusList.ProtoReflect.Descriptor instead.
func (*HealthStatusList) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{5}
}

func (x *HealthStatusList) GetStatuses() []*ServiceStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspacePath string                 `protobuf:"bytes,1,opt,name=workspace_path,json=workspacePath,proto3" json:"workspace_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_parallax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetWorkspacePath() string {
	if x != nil {
		return x.WorkspacePath
	}
	return ""
}

type FileChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	IsCollection  bool                   `protobuf:"varint,3,opt,name=is_collection,json=isCollection,proto3" json:"is_collection,omitempty"`
	IsEnvironment bool                   `protobuf:"varint,4,opt,name=is_environment,json=isEnvironment,proto3" json:"is_environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChangeEvent) Reset() {
	*x = FileChangeEvent{}
	mi := &file_parallax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChangeEvent) ProtoMessage() {}

func (x *FileChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChangeEvent.ProtoReflect.Descriptor instead.
func (*FileChangeEvent) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{7}
}

func (x *FileChangeEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChangeEvent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *FileChangeEvent) GetIsCollection() bool {
	if x != nil {
		return x.IsCollection
	}
	return false
}

func (x *FileChangeEvent) GetIsEnvironment() bool {
	if x != nil {
		return x.IsEnvironment
	}
	return false
}

type TrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficRequest) Reset() {
	*x = TrafficRequest{}
	mi := &file_parallax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficRequest) ProtoMessage() {}

func (x *TrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficRequest.ProtoReflect.Descriptor instead.
func (*TrafficRequest) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{8}
}

func (x *TrafficRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TrafficEntry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TimestampMs       int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Method            string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Url               string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	RequestHeaders    map[string]string      `protobuf:"bytes,5,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseHeaders   map[string]string      `protobuf:"bytes,6,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode        int32                  `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs         float64                `protobuf:"fixed64,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	RequestBodyBytes  int32                  `protobuf:"varint,9,opt,name=request_body_bytes,json=requestBodyBytes,proto3" json:"request_body_bytes,omitempty"`
	ResponseBodyBytes int32                  `protobuf:"varint,10,opt,name=response_body_bytes,json=responseBodyBytes,proto3" json:"response_body_bytes,omitempty"`
	ContentType       string                 `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Preview           string                 `protobuf:"bytes,12,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TrafficEntry) Reset() {
	*x = TrafficEntry{}
	mi := &file_parallax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficEntry) ProtoMessage() {}

func (x *TrafficEntry) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficEntry.ProtoReflect.Descriptor instead.
func (*TrafficEntry) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{9}
}

func (x *TrafficEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TrafficEntry) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *TrafficEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TrafficEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TrafficEntry) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *TrafficEntry) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *TrafficEntry) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *TrafficEntry) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TrafficEntry) GetRequestBodyBytes() int32 {
	if x != nil {
		return x.RequestBodyBytes
	}
	return 0
}

func (x *TrafficEntry) GetResponseBodyBytes() int32 {
	if x != nil {
		return x.ResponseBodyBytes
	}
	return 0
}

func (x *TrafficEntry) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *TrafficEntry) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

type TrafficList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TrafficEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficList) Reset() {
	*x = TrafficList{}
	mi := &file_parallax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficList) ProtoMessage() {}

func (x *TrafficList) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficList.ProtoReflect.Descriptor instead.
func (*TrafficList) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{10}
}

func (x *TrafficList) GetEntries() []*TrafficEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MockRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockRule) Reset() {
	*x = MockRule{}
	mi := &file_parallax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockRule) ProtoMessage() {}

func (x *MockRule) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockRule.ProtoReflect.Descriptor instead.
func (*MockRule) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{11}
}

func (x *MockRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MockRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MockRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MockRule) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *MockRule) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *MockRule) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *MockRule) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type MockRuleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*MockRule            `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockRuleList) Reset() {
	*x = MockRuleList{}
	mi := &file_parallax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockRuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockRuleList) ProtoMessage() {}

func (x *MockRuleList) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockRuleList.ProtoReflect.Descriptor instead.
func (*MockRuleList) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{12}
}

func (x *MockRuleList) GetRules() []*MockRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// =============================================================================
// Common
// =============================================================================
type GenericRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRequest) Reset() {
	*x = GenericRequest{}
	mi := &file_parallax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRequest) ProtoMessage() {}

func (x *GenericRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRequest.ProtoReflect.Descriptor instead.
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{13}
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_parallax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{14}
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_parallax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{15}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TargetIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetIDRequest) Reset() {
	*x = TargetIDRequest{}
	mi := &file_parallax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetIDRequest) ProtoMessage() {}

func (x *TargetIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parallax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetIDRequest.ProtoReflect.Descriptor instead.
func (*TargetIDRequest) Descriptor() ([]byte, []int) {
	return file_parallax_proto_rawDescGZIP(), []int{16}
}

func (x *TargetIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_parallax_proto protoreflect.FileDescriptor

const file_parallax_proto_rawDesc = "" +
	"\n" +
	"\x0eparallax.proto\x12\bparallax\"\xb5\x02\n" +
	"\x0eLoadTestConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12?\n" +
	"\aheaders\x18\x03 \x03(\v2%.parallax.LoadTestConfig.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1e\n" +
	"\n" +
	"concurrent\x18\x05 \x01(\x05R\n" +
	"concurrent\x12%\n" +
	"\x0etotal_requests\x18\x06 \x01(\x05R\rtotalRequests\x12!\n" +
	"\fduration_sec\x18\a \x01(\x05R\vdurationSec\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x10LoadTestProgress\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\x03R\tcompleted\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1f\n" +
	"\vcurrent_rps\x18\x03 \x01(\x01R\n" +
	"currentRps\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x120\n" +
	"\x06result\x18\x05 \x01(\v2\x18.parallax.LoadTestResultR\x06result\"\xab\x03\n" +
	"\x0eLoadTestResult\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x03R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x05 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x06 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\a \x01(\x01R\fp99LatencyMs\x12$\n" +
	"\x0emin_latency_ms\x18\b \x01(\x01R\fminLatencyMs\x12$\n" +
	"\x0emax_latency_ms\x18\t \x01(\x01R\fmaxLatencyMs\x12 \n" +
	"\freqs_per_sec\x18\n" +
	" \x01(\x01R\n" +
	"reqsPerSec\x12\x16\n" +
	"\x06errors\x18\v \x03(\tR\x06errors\x12\x1c\n" +
	"\thistogram\x18\f \x03(\x03R\thistogram\"\x87\x01\n" +
	"\rServiceTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\finterval_sec\x18\x04 \x01(\x05R\vintervalSec\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\"\xdd\x01\n" +
	"\rServiceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\x1f\n" +
	"\vstatus_code\x18\x06 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\flast_checked\x18\a \x01(\x03R\vlastChecked\x12\x1b\n" +
	"\terror_msg\x18\b \x01(\tR\berrorMsg\"G\n" +
	"\x10HealthStatusList\x123\n" +
	"\bstatuses\x18\x01 \x03(\v2\x17.parallax.ServiceStatusR\bstatuses\"5\n" +
	"\fWatchRequest\x12%\n" +
	"\x0eworkspace_path\x18\x01 \x01(\tR\rworkspacePath\"\x8f\x01\n" +
	"\x0fFileChangeEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12#\n" +
	"\ris_collection\x18\x03 \x01(\bR\fisCollection\x12%\n" +
	"\x0eis_environment\x18\x04 \x01(\bR\risEnvironment\"&\n" +
	"\x0eTrafficRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xfa\x04\n" +
	"\fTrafficEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12S\n" +
	"\x0frequest_headers\x18\x05 \x03(\v2*.parallax.TrafficEntry.RequestHeadersEntryR\x0erequestHeaders\x12V\n" +
	"\x10response_headers\x18\x06 \x03(\v2+.parallax.TrafficEntry.ResponseHeadersEntryR\x0fresponseHeaders\x12\x1f\n" +
	"\vstatus_code\x18\a \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x01R\tlatencyMs\x12,\n" +
	"\x12request_body_bytes\x18\t \x01(\x05R\x10requestBodyBytes\x12.\n" +
	"\x13response_body_bytes\x18\n" +
	" \x01(\x05R\x11responseBodyBytes\x12!\n" +
	"\fcontent_type\x18\v \x01(\tR\vcontentType\x12\x18\n" +
	"\apreview\x18\f \x01(\tR\apreview\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\vTrafficList\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.parallax.TrafficEntryR\aentries\"\x95\x02\n" +
	"\bMockRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x129\n" +
	"\aheaders\x18\x06 \x03(\v2\x1f.parallax.MockRule.HeadersEntryR\aheaders\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fMockRuleList\x12(\n" +
	"\x05rules\x18\x01 \x03(\v2\x12.parallax.MockRuleR\x05rules\"\x10\n" +
	"\x0eGenericRequest\"\r\n" +
	"\vStopRequest\"E\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fTargetIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2L\n" +
	"\rWorkerService\x12;\n" +
	"\x04Ping\x12\x18.parallax.GenericRequest\x1a\x19.parallax.GenericResponse2\xdf\x01\n" +
	"\x0fLoadTestService\x12E\n" +
	"\vRunLoadTest\x12\x18.parallax.LoadTestConfig\x1a\x1a.parallax.LoadTestProgress0\x01\x12@\n" +
	"\fStopLoadTest\x12\x15.parallax.StopRequest\x1a\x19.parallax.GenericResponse\x12C\n" +
	"\rGetLastResult\x12\x18.parallax.GenericRequest\x1a\x18.parallax.LoadTestResult2\xa1\x02\n" +
	"\rHealthService\x12?\n" +
	"\tAddTarget\x12\x17.parallax.ServiceTarget\x1a\x19.parallax.GenericResponse\x12D\n" +
	"\fRemoveTarget\x12\x19.parallax.TargetIDRequest\x1a\x19.parallax.GenericResponse\x12C\n" +
	"\vGetStatuses\x12\x18.parallax.GenericRequest\x1a\x1a.parallax.HealthStatusList\x12D\n" +
	"\rWatchStatuses\x12\x18.parallax.GenericRequest\x1a\x17.parallax.ServiceStatus0\x012\x9e\x01\n" +
	"\x0eWatcherService\x12E\n" +
	"\x0eWatchWorkspace\x12\x16.parallax.WatchRequest\x1a\x19.parallax.FileChangeEvent0\x01\x12E\n" +
	"\x10UnwatchWorkspace\x12\x16.parallax.WatchRequest\x1a\x19.parallax.GenericResponse2\xd6\x01\n" +
	"\fProxyService\x12=\n" +
	"\n" +
	"GetTraffic\x12\x18.parallax.TrafficRequest\x1a\x15.parallax.TrafficList\x12B\n" +
	"\fWatchTraffic\x12\x18.parallax.GenericRequest\x1a\x16.parallax.TrafficEntry0\x01\x12C\n" +
	"\fClearTraffic\x12\x18.parallax.GenericRequest\x1a\x19.parallax.GenericResponse2\xca\x01\n" +
	"\vMockService\x128\n" +
	"\aAddRule\x12\x12.parallax.MockRule\x1a\x19.parallax.GenericResponse\x12B\n" +
	"\n" +
	"RemoveRule\x12\x19.parallax.TargetIDRequest\x1a\x19.parallax.GenericResponse\x12=\n" +
	"\tListRules\x12\x18.parallax.GenericRequest\x1a\x16.parallax.MockRuleListB.Z,github.com/bluephoenix/parallax-worker/protob\x06proto3"

var (
	file_parallax_proto_rawDescOnce sync.Once
	file_parallax_proto_rawDescData []byte
)

func file_parallax_proto_rawDescGZIP() []byte {
	file_parallax_proto_rawDescOnce.Do(func() {
		file_parallax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parallax_proto_rawDesc), len(file_parallax_proto_rawDesc)))
	})
	return file_parallax_proto_rawDescData
}

var file_parallax_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_parallax_proto_goTypes = []any{
	(*LoadTestConfig)(nil),   // 0: parallax.LoadTestConfig
	(*LoadTestProgress)(nil), // 1: parallax.LoadTestProgress
	(*LoadTestResult)(nil),   // 2: parallax.LoadTestResult
	(*ServiceTarget)(nil),    // 3: parallax.ServiceTarget
	(*ServiceStatus)(nil),    // 4: parallax.ServiceStatus
	(*HealthStatusList)(nil), // 5: parallax.HealthStatusList
	(*WatchRequest)(nil),     // 6: parallax.WatchRequest
	(*FileChangeEvent)(nil),  // 7: parallax.FileChangeEvent
	(*TrafficRequest)(nil),   // 8: parallax.TrafficRequest
	(*TrafficEntry)(nil),     // 9: parallax.TrafficEntry
	(*TrafficList)(nil),      // 10: parallax.TrafficList
	(*MockRule)(nil),         // 11: parallax.MockRule
	(*MockRuleList)(nil),     // 12: parallax.MockRuleList
	(*GenericRequest)(nil),   // 13: parallax.GenericRequest
	(*StopRequest)(nil),      // 14: parallax.StopRequest
	(*GenericResponse)(nil),  // 15: parallax.GenericResponse
	(*TargetIDRequest)(nil),  // 16: parallax.TargetIDRequest
	nil,                      // 17: parallax.LoadTestConfig.HeadersEntry
	nil,                      // 18: parallax.TrafficEntry.RequestHeadersEntry
	nil,                      // 19: parallax.TrafficEntry.ResponseHeadersEntry
	nil,                      // 20: parallax.MockRule.HeadersEntry
}
var file_parallax_proto_depIdxs = []int32{
	17, // 0: parallax.LoadTestConfig.headers:type_name -> parallax.LoadTestConfig.HeadersEntry
	2,  // 1: parallax.LoadTestProgress.result:type_name -> parallax.LoadTestResult
	4,  // 2: parallax.HealthStatusList.statuses:type_name -> parallax.ServiceStatus
	18, // 3: parallax.TrafficEntry.request_headers:type_name -> parallax.TrafficEntry.RequestHeadersEntry
	19, // 4: parallax.TrafficEntry.response_headers:type_name -> parallax.TrafficEntry.ResponseHeadersEntry
	9,  // 5: parallax.TrafficList.entries:type_name -> parallax.TrafficEntry
	20, // 6: parallax.MockRule.headers:type_name -> parallax.MockRule.HeadersEntry
	11, // 7: parallax.MockRuleList.rules:type_name -> parallax.MockRule
	13, // 8: parallax.WorkerService.Ping:input_type -> parallax.GenericRequest
	0,  // 9: parallax.LoadTestService.RunLoadTest:input_type -> parallax.LoadTestConfig
	14, // 10: parallax.LoadTestService.StopLoadTest:input_type -> parallax.StopRequest
	13, // 11: parallax.LoadTestService.GetLastResult:input_type -> parallax.GenericRequest
	3,  // 12: parallax.HealthService.AddTarget:input_type -> parallax.ServiceTarget
	16, // 13: parallax.HealthService.RemoveTarget:input_type -> parallax.TargetIDRequest
	13, // 14: parallax.HealthService.GetStatuses:input_type -> parallax.GenericRequest
	13, // 15: parallax.HealthService.WatchStatuses:input_type -> parallax.GenericRequest
	6,  // 16: parallax.WatcherService.WatchWorkspace:input_type -> parallax.WatchRequest
	6,  // 17: parallax.WatcherService.UnwatchWorkspace:input_type -> parallax.WatchRequest
	8,  // 18: parallax.ProxyService.GetTraffic:input_type -> parallax.TrafficRequest
	13, // 19: parallax.ProxyService.WatchTraffic:input_type -> parallax.GenericRequest
	13, // 20: parallax.ProxyService.ClearTraffic:input_type -> parallax.GenericRequest
	11, // 21: parallax.MockService.AddRule:input_type -> parallax.MockRule
	16, // 22: parallax.MockService.RemoveRule:input_type -> parallax.TargetIDRequest
	13, // 23: parallax.MockService.ListRules:input_type -> parallax.GenericRequest
	15, // 24: parallax.WorkerService.Ping:output_type -> parallax.GenericResponse
	1,  // 25: parallax.LoadTestService.RunLoadTest:output_type -> parallax.LoadTestProgress
	15, // 26: parallax.LoadTestService.StopLoadTest:output_type -> parallax.GenericResponse
	2,  // 27: parallax.LoadTestService.GetLastResult:output_type -> parallax.LoadTestResult
	15, // 28: parallax.HealthService.AddTarget:output_type -> parallax.GenericResponse
	15, // 29: parallax.HealthService.RemoveTarget:output_type -> parallax.GenericResponse
	5,  // 30: parallax.HealthService.GetStatuses:output_type -> parallax.HealthStatusList
	4,  // 31: parallax.HealthService.WatchStatuses:output_type -> parallax.ServiceStatus
	7,  // 32: parallax.WatcherService.WatchWorkspace:output_type -> parallax.FileChangeEvent
	15, // 33: parallax.WatcherService.UnwatchWorkspace:output_type -> parallax.GenericResponse
	10, // 34: parallax.ProxyService.GetTraffic:output_type -> parallax.TrafficList
	9,  // 35: parallax.ProxyService.WatchTraffic:output_type -> parallax.TrafficEntry
	15, // 36: parallax.ProxyService.ClearTraffic:output_type -> parallax.GenericResponse
	15, // 37: parallax.MockService.AddRule:output_type -> parallax.GenericResponse
	15, // 38: parallax.MockService.RemoveRule:output_type -> parallax.GenericResponse
	12, // 39: parallax.MockService.ListRules:output_type -> parallax.MockRuleList
	24, // [24:40] is the sub-list for method output_type
	8,  // [8:24] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_parallax_proto_init() }
func file_parallax_proto_init() {
	if File_parallax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parallax_proto_rawDesc), len(file_parallax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   6,
		},
		GoTypes:           file_parallax_proto_goTypes,
		DependencyIndexes: file_parallax_proto_depIdxs,
		MessageInfos:      file_parallax_proto_msgTypes,
	}.Build()
	File_parallax_proto = out.File
	file_parallax_proto_goTypes = nil
	file_parallax_proto_depIdxs = nil
}
